#!/bin/bash
# envdeploy - Environment Setup Module (Fixed)

set -euo pipefail

PROJECT_DIR="${1:-.}"
PROJECT_NAME="${2:-unknown-project}"
MODULE_NAME="${PROJECT_NAME//-/_}"

cd "$PROJECT_DIR" || { echo "Error: Cannot access project directory"; exit 1; }

echo "🐍 Setting up Python environment for: $PROJECT_NAME"

# Create project structure
mkdir -p "src/$MODULE_NAME" tests

# Create clean pyproject.toml
cat > pyproject.toml << PY
[project]
name = "$PROJECT_NAME"
version = "0.1.0"
description = "Generated by envdeploy-cli"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
]

[project.scripts]
run = "$MODULE_NAME.main:app"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"
PY

# Create FastAPI main.py
cat > "src/$MODULE_NAME/main.py" << APP
from fastapi import FastAPI

app = FastAPI(title="$PROJECT_NAME")

@app.get("/")
async def root():
    return {"message": "Hello from envdeploy-cli generated project! 🚀"}

@app.get("/health")
async def health():
    return {"status": "healthy"}
APP

echo "✅ Project structure created"

# Create virtual environment
if [ ! -d "venv" ]; then
    python3 -m venv venv
    echo "✅ Virtual environment created"
fi

# Install dependencies
echo "📦 Installing dependencies..."
source venv/bin/activate
pip install --upgrade pip
pip install -e .

echo "✅ Dependencies installed successfully"
echo "🎉 Environment setup completed!"
echo ""
echo "To run the project:"
echo "   cd $PROJECT_DIR"
echo "   source venv/bin/activate"
echo "   uvicorn $MODULE_NAME.main:app --reload"
